FROM europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/jre:openjdk-21{% if appd is defined %}-appdynamics{% endif %}

COPY init-scripts/ep-jvm-tuning.sh /init-scripts/

COPY {{ build_jar }} /app/app.jar
{% if on_prem is defined and on_prem==true %}COPY nais/export-vault-secrets.sh /init-scripts/
{% endif %}{% if appd is defined %}
ENV APPD_NAME {{ appd.name }}
ENV APPD_TIER {{ appd.tier }}
ENV APPD_ENABLED {{ appd.enabled|lower }}
{% endif %}
CMD ["-jar","app.jar"]